<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE DAOConfiguration [

	<!ELEMENT DAOConfiguration (DAOStatements+)>

	<!ELEMENT DAOStatements (SQLStatement+)>
	<!ATTLIST DAOStatements
		database CDATA #REQUIRED
	>
 
	<!ELEMENT SQLStatement (SQLFragment+)>
	<!ATTLIST SQLStatement
		method (COUNT_TABLE|GET_ITEMS_REFERENCE|CHECK_TABLE|CHECK_TABLE_USERS|GET_MAX_ITEMID
                    |CREATE_USERS_TABLE|INSERT_USER|INSERT_USER_FULL|UPDATE_USER_USERNAME
                    |UPDATE_USER_ACCESS|UPDATE_USER_PASSWORD|DELETE_USER|GET_USER
                    |GET_USER_LIMIT|CHECK_USER_PASSWORD|DROP_TABLE|TRUNCATE_TABLE
                    |CREATE_ROLES_TABLE|INSERT_ROL|UPDATE_ROL|DELETE_ROL|GET_ROLES_LIST
                    |CREATE_PERMISSIONS_TABLE|INSERT_PERMISSION|UPDATE_PERMISSION|DELETE_PERMISSION|GET_PERMISSIONS_LIST
                    |CREATE_PERMISSION_ROLE_TABLE|GET_PERMISSION_ROLE_LIST|DELETE_PERMISSION_ROLE|INSERT_PERMISSION_ROLE
                    |GET_PERMISSION_BY_ROLE_LIST|GET_ROLE|CREATE_ROLE_USER_TABLE|INSERT_ROLE_USER|GET_ROLE_USER_LIST
                    |DELETE_ROLE_USER|HAS_PERMISSION|GET_USER_ROLE
                    |CREATE_PERSONS_TABLE
                    |GET_PERSON|GET_PERSON_LIMIT|INSERT_PERSON|UPDATE_PERSON|GET_ID_PERSON|DELETE_PERSON|DELETE_PERSON_WHERE
                    |CREATE_CONFIG_TABLE|GET_CONFIG|DELETE_CONFIG|UPDATE_CONFIG|EXIST_CONFIG
                    |ADD_CONFIG
                    |EXIST_CLAVE|GET_MAX_ID|COUNT_TABLE2|EXIST_CLAVE_MULT
                    |CREATE_PRODUCTS_TABLE|ADD_PRODUCT|GET_PRODUCT|DELETE_PRODUCT|UPDATE_PRODUCT|GET_PRODUCT_BY_PRESS_ID
                    |CREATE_INGREDIENTS_TABLE|ADD_INGREDIENT|GET_INGREDIENT|DELETE_INGREDIENT|UPDATE_INGREDIENT
                    |CREATE_PRODUCT_INGREDIENT_TABLE|GET_INGREDIENTS_BY_PRODUCT
                    |CREATE_ADDITIONALS_TABLE|ADD_ADDITIONAL|GET_ADDITIONAL|DELETE_ADDITIONAL|UPDATE_ADDITIONAL
                    |CREATE_INVOICES_TABLE|ADD_INVOICE|GET_INVOICE|DELETE_INVOICE|UPDATE_INVOICE
                    |CREATE_ORDERS_TABLE|ADD_ORDER|GET_ORDER|DELETE_ORDER|UPDATE_ORDER
                    |CREATE_WAITERS_TABLE|CREATE_TABLES_TABLE|CREATE_INVOICE_PRODUCT_TABLE
                    |GET_WAITERS|GET_TABLES|ADD_INVOICE_PRODUCT|GET_INVOICE_PRODUCT
                    |CREATE_ADDITIONAL_PRODUCT_TABLE|ADD_ADDITIONAL_PRODUCT|GET_ADDITIONAL_PRODUCT
                    |CREATE_EXCLUSION_PRODUCT_TABLE|ADD_EXCLUSION_PRODUCT|GET_EXCLUSION_PRODUCT
                    |GET_FIRST_REGISTRO|GET_LAST_REGISTRO
                    |CREATE_CLIENTS_TABLE|GET_CLIENT|ADD_CLIENT|DELETE_CLIENT|UPDATE_CLIENT
                    |CREATE_PRESENTATION_PRODUCT_TABLE|GET_PRESENTATIONS_BY_PRODUCT|GET_PRESENTATION_BY_DEFAULT|GET_PRESENTATION
                    |GET_ALL_PRESENTATIONS_BY_PRODUCT
                    |CREATE_CYCLES_TABLE|GET_CYCLE|ADD_CYCLE|DELETE_CYCLE|UPDATE_CYCLE|GET_LAST_CYCLE
                    |CREATE_OTHER_PRODUCTS_TABLE|GET_OTHER_PRODUCT|ADD_OTHER_PRODUCT|DELETE_OTHER_PRODUCT
                    |CREATE_INVOICE_OTHER_PRODUCT_TABLE|ADD_INVOICE_OTHER_PRODUCT
                    |GET_CATEGORIES_SORTED|GET_ALL_CATEGORIES|GET_CATEGORY
                    |CREATE_EXPENSES_INCOMES_TABLE|ADD_EXPENSE_INCOME|GET_EXPENSE_INCOME
                    |CREATE_EXPENSES_CATEGORIES_TABLE|ADD_EXPENSES_CATEGORY|GET_EXPENSES_CATEGORY|UPDATE_EXPENSES_CATEGORY
                    |DELETE_EXPENSES_CATEGORY|GET_INVOICE_BY_PRODUCT
                    |CREATE_INVENTORY_TABLE|GET_ITEM|ADD_ITEM|UPDATE_ITEM
                    |ADD_UNIT|GET_UNIT|UPDATE_UNIT|DELETE_UNIT|CREATE_UNITS_TABLE
                    |CREATE_INVENTORY_PRODUCT_TABLE|ADD_INVENTORY_PRODUCT|CHECK_INVENTORY|CHECK_INVENTORY_PRODUCT
                    |ADD_INVENTORY_PRESENTATION|DELETE_ITEM_PRES|DELETE_ITEM
                    |UPDATE_INVENTORY_QUANTITY|ADD_INVENTORY_QUANTITY
                    |CREATE_CONCILIACIONES_TABLE|ADD_CONCILIACION|GET_CONCILIACION|UPDATE_CONCILIACION|DELETE_CONCILIACION
                    |ADD_LOCATION|GET_LOCATION|UPDATE_LOCATION|DELETE_LOCATION|CREATE_LOCATIONS_TABLE
                    |CREATE_INVENTORY_REGISTER_TABLE|ADD_INVENTORY_EVENT|GET_INVENTORY_EVENT_LIST
                    |GET_PRODUCTS_OUT_INVENTORY|GET_PRESENTATIONS_OUT_INVENTORY
                    |GET_ITEM_PRESENTATIONS
                    |GET_PRODUCTS_SALES
                    |GET_LAST_INVOICE_BY_CLIENT 
                    |ADD_PAYMENT|GET_PAYMENT|UPDATE_PAYMENT|DELETE_PAYMENT|CREATE_PAYMENTS_TABLE
                    |GET_TAGS_INVENTORY_LIST
                    |CREATE_INVENTORY_SNAPSHOT_TABLE|ADD_INVENTORY_SNAPSHOT_ITEM|GET_INVENTORY_SNAPSHOT_ITEM
                    |UPDATE_INVENTORY_SNAPSHOT_ITEM
                    |COUNT_ITEM_SNAP_EVENT|COUNT_ITEM_CONCILIATION_EVENT
                    |GET_PRODUCTS_BY_VARPRICE_RANK_LIST
                    |CREATE_CATEGORIES_TABLE|ADD_CATEGORY|GET_CATEGORY_PROD|UPDATE_CATEGORY
                    |ADD_PRESENTATION|UPDATE_PRESENTATION|UPDATE_PRESENTATION_TO_DEFAULT|UPDATE_PRESENTATION_TO_DEFAULT_BY_ID
                    |ADD_ORDER_PRODUCT|GET_ORDER_PRODUCT
                    |CREATE_STATIONS_TABLE|ADD_STATION|GET_STATIONS|CREATE_PRODUCT_STATION_TABLE|GET_PRODUCT_STATIONS
                    |GET_STATION_BY_ID
                    |COUNT_UNINVOICED_PRODUCTS|GET_UNINVOICED_PRODUCTS                    
                    ) #REQUIRED
                    
	>

	<!ELEMENT SQLFragment (#PCDATA)>
	<!ATTLIST SQLFragment
		excludeIfNamedParamEmpty (TRUE|FALSE) "FALSE"
	>
]>



<DAOConfiguration>	
    <!-- MYSQL -->
    <DAOStatements database="mysql">
        <SQLStatement method="COUNT_TABLE">
            <SQLFragment>
                SELECT count(*) FROM ({query}) AS counted
            </SQLFragment>
        </SQLStatement>

        <SQLStatement method="CHECK_TABLE">
            <SQLFragment>
                SELECT count(*) FROM {table}
            </SQLFragment>
        </SQLStatement>
		
        <SQLStatement method="CREATE_USERS_TABLE">
            <SQLFragment>
                CREATE TABLE users (
                id INTEGER NOT NULL AUTO_INCREMENT,
                username VARCHAR(100),
                password VARCHAR(100),
                access_level VARCHAR(100),
                createdTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                UNIQUE (username),
                PRIMARY KEY (id)
                );
            </SQLFragment>
        </SQLStatement>
		
        <SQLStatement method="INSERT_USER">
            <SQLFragment>
                INSERT INTO users (username,password,access_level) VALUES (?, ?, ?);
            </SQLFragment>
        </SQLStatement>
		
        <SQLStatement method="INSERT_USER_FULL">
            <SQLFragment>
                INSERT INTO users VALUES (?, ?, ?, ?);
            </SQLFragment>
        </SQLStatement>
		
        <SQLStatement method="UPDATE_USER_USERNAME">
            <SQLFragment>
                UPDATE users SET username = ? WHERE id = ?;
            </SQLFragment>
        </SQLStatement>
		
        <SQLStatement method="UPDATE_USER_ACCESS">
            <SQLFragment>
                UPDATE users SET access_level = ? WHERE id = ?;
            </SQLFragment>
        </SQLStatement>
		
        <SQLStatement method="UPDATE_USER_PASSWORD">
            <SQLFragment>
                UPDATE users SET password = ? WHERE id = ?;
            </SQLFragment>
        </SQLStatement>
		
        <SQLStatement method="DELETE_USER">
            <SQLFragment>
                DELETE FROM users WHERE username = ?;
            </SQLFragment>
        </SQLStatement>
		
        <SQLStatement method="GET_USER_LIMIT">
            <SQLFragment>
                SELECT
            </SQLFragment>
            <SQLFragment>
                id, username, access_level
                FROM users
            </SQLFragment>
            <SQLFragment excludeIfNamedParamEmpty="TRUE">
                WHERE {where}
            </SQLFragment>
            <SQLFragment excludeIfNamedParamEmpty="TRUE">
                ORDER BY {orderby}
            </SQLFragment>
            <SQLFragment excludeIfNamedParamEmpty="TRUE">
                LIMIT ?, ?
            </SQLFragment>
        </SQLStatement>
		
        <SQLStatement method="GET_USER">
            <SQLFragment>
                SELECT
            </SQLFragment>
            <SQLFragment>
                id, username, access_level
                FROM users
            </SQLFragment>
            <SQLFragment excludeIfNamedParamEmpty="TRUE">
                WHERE {where}
            </SQLFragment>
            <SQLFragment excludeIfNamedParamEmpty="TRUE">
                ORDER BY {orderby}
            </SQLFragment>
        </SQLStatement>
		
        <SQLStatement method="CHECK_USER_PASSWORD">
            <SQLFragment>
                SELECT password, id, access_level FROM users WHERE username = ? AND STRCMP(BINARY password, ?) = 0;
            </SQLFragment>
        </SQLStatement>		
        
        <SQLStatement method="CREATE_ROLES_TABLE">
            <SQLFragment>
                CREATE TABLE roles (
                id INTEGER NOT NULL AUTO_INCREMENT,
                name VARCHAR(100),
                display_name VARCHAR(255),
                description VARCHAR(255),
                createdTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                UNIQUE (name),
                PRIMARY KEY (id)
                );
            </SQLFragment>
        </SQLStatement>
        
        <SQLStatement method="GET_ROLES_LIST">
            <SQLFragment>
                SELECT
            </SQLFragment>
            <SQLFragment>
                *
                FROM roles
            </SQLFragment>
            <SQLFragment excludeIfNamedParamEmpty="TRUE">
                WHERE {where}
            </SQLFragment>    
            <SQLFragment excludeIfNamedParamEmpty="TRUE">
                ORDER BY {orderby} 
            </SQLFragment>
            
        </SQLStatement>
        
        <SQLStatement method="GET_ROLE">
            <SQLFragment>
                SELECT
            </SQLFragment>
            <SQLFragment>
                id, name
                FROM roles
            </SQLFragment>
            <SQLFragment excludeIfNamedParamEmpty="TRUE">
                WHERE {where}
            </SQLFragment>
        </SQLStatement>
        
        <SQLStatement method="INSERT_ROL">
            <SQLFragment>
                INSERT INTO roles (name,display_name,description ) VALUES (?, ?, ?);
            </SQLFragment>
        </SQLStatement>
        
        <SQLStatement method="UPDATE_ROL">
            <SQLFragment>
                UPDATE roles SET 
                name= ?,
                display_name= ?,
                description= ?
                WHERE id = ?;
            </SQLFragment>
        </SQLStatement>
        
        <SQLStatement method="DELETE_ROL">
            <SQLFragment>
                DELETE FROM roles WHERE name = ?;
            </SQLFragment>
        </SQLStatement>
        
        
        <SQLStatement method="CREATE_PERMISSIONS_TABLE">
            <SQLFragment>
                CREATE TABLE permissions (
                id INTEGER NOT NULL AUTO_INCREMENT,
                name VARCHAR(100),
                display_name VARCHAR(255),
                description VARCHAR(255),
                UNIQUE (name),
                PRIMARY KEY (id)
                );
            </SQLFragment>
        </SQLStatement>
        
        <SQLStatement method="INSERT_PERMISSION">
            <SQLFragment>
                INSERT INTO permissions (name,display_name,description) VALUES (?, ?, ?);
            </SQLFragment>
        </SQLStatement>
        
        <SQLStatement method="UPDATE_PERMISSION">
            <SQLFragment>
                UPDATE permissions SET 
                name= ?,
                display_name= ?,
                description= ?
                WHERE id = ?;
            </SQLFragment>
        </SQLStatement>
        
        <SQLStatement method="DELETE_PERMISSION">
            <SQLFragment>
                DELETE FROM permissions WHERE id = ?;
            </SQLFragment>
        </SQLStatement>
        
        <SQLStatement method="GET_PERMISSIONS_LIST">
            <SQLFragment>
                SELECT
            </SQLFragment>
            <SQLFragment>
                *
                FROM permissions
            </SQLFragment>            
            <SQLFragment excludeIfNamedParamEmpty="TRUE">
                WHERE {where}
            </SQLFragment>    
            <SQLFragment excludeIfNamedParamEmpty="TRUE">
                ORDER BY {orderby} 
            </SQLFragment>
        </SQLStatement>
        
        <SQLStatement method="CREATE_PERMISSION_ROLE_TABLE">
            <SQLFragment>
                CREATE TABLE permission_role (
                permission_id INTEGER NOT NULL,
                role_id INTEGER NOT NULL,
                FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE ON UPDATE CASCADE,
                FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE ON UPDATE CASCADE
                );
            </SQLFragment>
        </SQLStatement>
        
        <SQLStatement method="INSERT_PERMISSION_ROLE">
            <SQLFragment>
                INSERT INTO permission_role VALUES (?, ?);
            </SQLFragment>
        </SQLStatement>
        
        <SQLStatement method="GET_PERMISSION_ROLE_LIST">
            <SQLFragment>
                SELECT
            </SQLFragment>
            <SQLFragment>
                *
                FROM permission_role
            </SQLFragment>            
            <SQLFragment excludeIfNamedParamEmpty="TRUE">
                WHERE {where}
            </SQLFragment>    
            <SQLFragment excludeIfNamedParamEmpty="TRUE">
                ORDER BY {orderby} 
            </SQLFragment>
        </SQLStatement>
        
        <SQLStatement method="GET_PERMISSION_BY_ROLE_LIST">
            <SQLFragment>
                SELECT
            </SQLFragment>
            <SQLFragment>
                p.id, 
                p.name,
                p.display_name,
                p.description
                FROM permissions p, roles r, permission_role pr
            </SQLFragment>            
            <SQLFragment>
                WHERE pr.permission_id=p.id and r.id=pr.role_id and r.id=?
            </SQLFragment>    
            <SQLFragment excludeIfNamedParamEmpty="TRUE">
                ORDER BY {orderby} 
            </SQLFragment>
        </SQLStatement>
        
        <SQLStatement method="DELETE_PERMISSION_ROLE">
            <SQLFragment>
                DELETE FROM permission_role WHERE role_id = ?;
            </SQLFragment>
        </SQLStatement>
        
        <SQLStatement method="CREATE_ROLE_USER_TABLE">
            <SQLFragment>
                CREATE TABLE role_user (
                user_id INTEGER NOT NULL,
                role_id INTEGER NOT NULL,
                UNIQUE(user_id),
                FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
                FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE ON UPDATE CASCADE
                );
            </SQLFragment>
        </SQLStatement>
        
        <SQLStatement method="INSERT_ROLE_USER">
            <SQLFragment>
                INSERT INTO role_user VALUES (?, ?);
            </SQLFragment>
        </SQLStatement>
        
        <SQLStatement method="GET_ROLE_USER_LIST">
            <SQLFragment>
                SELECT
            </SQLFragment>
            <SQLFragment>
                *
                FROM role_user
            </SQLFragment>            
            <SQLFragment excludeIfNamedParamEmpty="TRUE">
                WHERE {where}
            </SQLFragment>    
            <SQLFragment excludeIfNamedParamEmpty="TRUE">
                ORDER BY {orderby} 
            </SQLFragment>
        </SQLStatement>
        
        <SQLStatement method="DELETE_ROLE_USER">
            <SQLFragment>
                DELETE FROM role_user WHERE user_id = ?;
            </SQLFragment>
        </SQLStatement>
        
        <SQLStatement method="HAS_PERMISSION">
            <SQLFragment>
                SELECT count(*) 
                FROM permission_role pr, role_user ru
                WHERE pr.role_id = ru.role_id AND ru.user_id=? AND pr.permission_id=?
            </SQLFragment>
        </SQLStatement>
        
        
        <SQLStatement method="GET_USER_ROLE">
            <SQLFragment>
                SELECT r.name 
                FROM role_user ru, roles r, users u 
                WHERE ru.role_id = r.id AND u.id=ru.user_id AND u.id=?
            </SQLFragment>
        </SQLStatement>
        
          
                	
        <SQLStatement method="CREATE_PERSONS_TABLE">
            <SQLFragment>
                CREATE TABLE persons (
                id INTEGER AUTO_INCREMENT,
                identification INTEGER NOT NULL UNIQUE,
                firstName1 VARCHAR(255),
                firstName2 VARCHAR(255),
                lastName1 VARCHAR(255),
                lastName2 VARCHAR(255),
                lider INTEGER,					
                cellphone VARCHAR(15),
                profession VARCHAR(255),
                address VARCHAR(255),
                place1 VARCHAR(255),
                typePlace VARCHAR(255),
                neighborhood VARCHAR(255),                
                birthday DATE,
                email VARCHAR(255),
                votingPlace VARCHAR(255),
                votingTable INTEGER,
                witness TINYINT(1) DEFAULT '0',
                jury TINYINT(1) DEFAULT '0',
                volunteer TINYINT(1) DEFAULT '0',
                hardvote TINYINT(1) DEFAULT '0',
                giveVehicle TINYINT(1) DEFAULT '0',
                typeVehicle VARCHAR(255),
                compromise VARCHAR(255),
                photo BLOB DEFAULT NULL,
                createdTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                lastUpdatedTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                PRIMARY KEY (id));
            </SQLFragment>
        </SQLStatement>		
        
        <SQLStatement method="GET_PERSON">
            <SQLFragment>
                SELECT
            </SQLFragment>
            <SQLFragment>
                *
                FROM persons
            </SQLFragment>
            <SQLFragment excludeIfNamedParamEmpty="TRUE">
                WHERE {where}
            </SQLFragment>    
            <SQLFragment excludeIfNamedParamEmpty="TRUE">
                ORDER BY {orderby} 
            </SQLFragment>
            
        </SQLStatement>
        
        <SQLStatement method="GET_ID_PERSON">
            <SQLFragment>
                SELECT
            </SQLFragment>
            <SQLFragment>
                identification
                FROM persons
            </SQLFragment>
            <SQLFragment excludeIfNamedParamEmpty="TRUE">
                WHERE {where}
            </SQLFragment>    
            <SQLFragment excludeIfNamedParamEmpty="TRUE">
                ORDER BY {orderby} 
            </SQLFragment>
            
        </SQLStatement>
        
        <SQLStatement method="GET_PERSON_LIMIT">
            <SQLFragment>
                SELECT
            </SQLFragment>
            <SQLFragment>
                *
                FROM persons
            </SQLFragment>
            <SQLFragment excludeIfNamedParamEmpty="TRUE">
                WHERE {where}
            </SQLFragment>    
            <SQLFragment excludeIfNamedParamEmpty="TRUE">
                ORDER BY {orderby} 
            </SQLFragment>
            <SQLFragment excludeIfNamedParamEmpty="TRUE">
                LIMIT {start}, {num}
            </SQLFragment>
        </SQLStatement>
        
        
        <SQLStatement method="UPDATE_PERSON">
            <SQLFragment>
                UPDATE persons SET 
                firstName1=?,
                firstName2=?,
                lastName1=?,
                lastName2=?,
                lider=?,
                cellphone=?,
                profession=?,
                address=?,
                place1=?,
                typePlace=?,
                neighborhood=?,                
                birthday=?,
                email=?,
                votingPlace=?,
                votingTable=?,
                witness=?,
                jury=?,
                volunteer=?,
                hardvote=?,
                giveVehicle=?,
                typeVehicle=?,
                compromise=?,
                photo=? 
                WHERE identification = ?
            </SQLFragment>
        </SQLStatement>
        
        <SQLStatement method="INSERT_PERSON">
            <SQLFragment>
                INSERT INTO persons (identification,firstName1,firstName2,
                lastName1,lastName2,lider,cellphone,profession,
                address,place1,typePlace,neighborhood,birthday,email,votingPlace,
                votingTable,witness,jury,volunteer,hardvote,giveVehicle,typeVehicle,
                compromise,photo) 
                VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);
            </SQLFragment>
        </SQLStatement>	
                
        <SQLStatement method="DELETE_PERSON">
            <SQLFragment>
                DELETE FROM persons WHERE identification = ?;
            </SQLFragment>
        </SQLStatement>		
        
        <SQLStatement method="DELETE_PERSON_WHERE">
            <SQLFragment>
                DELETE FROM persons
            </SQLFragment>
            <SQLFragment excludeIfNamedParamEmpty="TRUE">
                WHERE {where}
            </SQLFragment>
        </SQLStatement>		
                       
        <SQLStatement method="DROP_TABLE">
            <SQLFragment>
                DROP TABLE {table};
            </SQLFragment>
        </SQLStatement>
        
        <SQLStatement method="TRUNCATE_TABLE">
            <SQLFragment>
                TRUNCATE TABLE {table};
            </SQLFragment>
        </SQLStatement>
       
        <SQLStatement method="CHECK_TABLE_USERS">
            <SQLFragment>
                SELECT count(*) FROM users WHERE 1=1
            </SQLFragment>
        </SQLStatement> 
        
        <SQLStatement method="COUNT_TABLE2">
            <SQLFragment>
                SELECT count(*) FROM ? WHERE 1=1;
            </SQLFragment>
        </SQLStatement>  
        
        <SQLStatement method="CREATE_CONFIG_TABLE">
            <SQLFragment>
                CREATE TABLE config (
                id INTEGER AUTO_INCREMENT,
                code VARCHAR(100) NOT NULL,
                value VARCHAR(255),
                type VARCHAR(255),
                user VARCHAR(100) NOT NULL,
                device VARCHAR(100) NOT NULL,
                PRIMARY KEY (id),
                UNIQUE KEY unique_id(code,user,device));
            </SQLFragment>
        </SQLStatement>	
        
        <SQLStatement method="GET_CONFIG">
            <SQLFragment>
                SELECT
            </SQLFragment>
            <SQLFragment>
                *
                FROM config
            </SQLFragment>
            <SQLFragment excludeIfNamedParamEmpty="TRUE">
                WHERE {where}
            </SQLFragment>            
        </SQLStatement>
        
        <SQLStatement method="ADD_CONFIG">
            <SQLFragment>
                INSERT INTO config (code,value, type, user, device) VALUES (?,?,?,?,?)
            </SQLFragment>
            <SQLFragment>
                ON DUPLICATE KEY UPDATE value= VALUES(value), type=VALUES(type)
            </SQLFragment>
        </SQLStatement>        
        
        <SQLStatement method="DELETE_CONFIG">
            <SQLFragment>
                DELETE FROM config WHERE code  = ?;
            </SQLFragment>
        </SQLStatement>
        
        <SQLStatement method="UPDATE_CONFIG">
            <SQLFragment>
                UPDATE config SET 
                value=?,
                type=? 
                WHERE code = ? AND user = ? AND device = ?
            </SQLFragment>
        </SQLStatement>    
        
        <SQLStatement method="EXIST_CONFIG">
            <SQLFragment>
                SELECT count(code) FROM config WHERE code=? AND user=? AND device=?;
            </SQLFragment>
        </SQLStatement>    
        
        <SQLStatement method="EXIST_CLAVE">
            <SQLFragment>
                SELECT count({query}) FROM {table} WHERE {query}={key};
            </SQLFragment>
        </SQLStatement>
        
        <SQLStatement method="EXIST_CLAVE_MULT">
            <SQLFragment>
                SELECT count({query}) FROM {table} WHERE {key};
            </SQLFragment>
        </SQLStatement>
        
        <SQLStatement method="GET_MAX_ID">
            <SQLFragment>
                SELECT max(id) FROM {table};
            </SQLFragment>
        </SQLStatement>
        
        
        
        <SQLStatement method="CREATE_PRODUCTS_TABLE">
            <SQLFragment>
                CREATE TABLE products(
                id INTEGER AUTO_INCREMENT,
                name VARCHAR(255) NOT NULL UNIQUE,
                code VARCHAR(255) NOT NULL UNIQUE,      
                description VARCHAR(500),
                price DECIMAL(20,2),
                variable TINYINT(1),
                image VARCHAR(255),
                category VARCHAR(25),
                enabled TINYINT(1) DEFAULT 1, 
                PRIMARY KEY (id)
                )ENGINE=InnoDB DEFAULT CHARSET=latin1;
            </SQLFragment>
        </SQLStatement>	
        
        <SQLStatement method="ADD_PRODUCT">
            <SQLFragment>
                INSERT INTO products (name,code, description, price, image, category, variable, enabled) VALUES (?,?,?,?,?,?,?,?);
            </SQLFragment>
        </SQLStatement>        
        
        <SQLStatement method="GET_PRODUCT">
            <SQLFragment>
                SELECT
            </SQLFragment>
            <SQLFragment>
                * FROM products
            </SQLFragment>
            <SQLFragment excludeIfNamedParamEmpty="TRUE">
                WHERE {where}
            </SQLFragment>    
            <SQLFragment excludeIfNamedParamEmpty="TRUE">
                ORDER BY {orderby}
            </SQLFragment>        
        </SQLStatement>
        
        <SQLStatement method="DELETE_PRODUCT">
            <SQLFragment>
                DELETE FROM products WHERE code = ?;
            </SQLFragment>
        </SQLStatement>
        
        <SQLStatement method="UPDATE_PRODUCT">
            <SQLFragment>
                UPDATE products SET 
                name=?,                
                code=?,                
                description=?,
                price=?,
                image=?,
                category=?,
                variable=?,
                enabled=? 
                WHERE id = ?
            </SQLFragment>
        </SQLStatement> 
        
        <SQLStatement method="GET_PRODUCT_BY_PRESS_ID">
            <SQLFragment>
                SELECT
                p.id,p.name,p.code,p.description,p.price,p.variable,p.image,p.category,p.enabled
            </SQLFragment>
            <SQLFragment>
                FROM products p, presentation_product pp
            </SQLFragment>
            <SQLFragment excludeIfNamedParamEmpty="TRUE">
                WHERE p.id=pp.product_id AND {where}
            </SQLFragment>
        </SQLStatement>
        
        <SQLStatement method="CREATE_INGREDIENTS_TABLE">
            <SQLFragment>
                CREATE TABLE ingredients(
                id INTEGER AUTO_INCREMENT,
                name VARCHAR(255) NOT NULL UNIQUE,
                code VARCHAR(255) NOT NULL UNIQUE,      
                medida VARCHAR(25),                
                PRIMARY KEY (id)
                )ENGINE=InnoDB DEFAULT CHARSET=latin1;
            </SQLFragment>
        </SQLStatement>	
        
        <SQLStatement method="ADD_INGREDIENT">
            <SQLFragment>
                INSERT INTO ingredients (name,code,medida) VALUES (?,?,?);
            </SQLFragment>
        </SQLStatement>        
        
        <SQLStatement method="GET_INGREDIENT">
            <SQLFragment>
                SELECT
            </SQLFragment>
            <SQLFragment>
                * FROM ingredients
            </SQLFragment>
            <SQLFragment excludeIfNamedParamEmpty="TRUE">
                WHERE {where}
            </SQLFragment>    
            <SQLFragment excludeIfNamedParamEmpty="TRUE">
                ORDER BY {orderby}
            </SQLFragment>        
        </SQLStatement>
        
        <SQLStatement method="DELETE_INGREDIENT">
            <SQLFragment>
                DELETE FROM ingredients WHERE code = ?;
            </SQLFragment>
        </SQLStatement>
        
        <SQLStatement method="UPDATE_INGREDIENT">
            <SQLFragment>
                UPDATE ingredients SET 
                name=?,                
                medida=? 
                WHERE code = ?
            </SQLFragment>
        </SQLStatement> 
        
        
        
        <SQLStatement method="CREATE_PRODUCT_INGREDIENT_TABLE">
            <SQLFragment>
                CREATE TABLE product_ingredient (
                product_id INTEGER NOT NULL,
                ingredient_id INTEGER NOT NULL,
                cantidad INTEGER,
                opcional TINYINT(1) DEFAULT '0',
                FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE ON UPDATE CASCADE,
                FOREIGN KEY (ingredient_id) REFERENCES ingredients(id) ON DELETE CASCADE ON UPDATE CASCADE
                );
            </SQLFragment>
        </SQLStatement>
        